### PR TITLE
Fix #38 Translation: Стилизуем placeholder при помощи CSS.

### LINKED ISSUE #38: Translate: Стилизуем placeholder при помощи CSS
http://html5.by/blog/placeholder/

### PR DESCRIPTION
**Pull request by talgautb**
My first translation
Don't judge me too harshly :)

### CODE REVIEW

**Comment by talgautb** [comment]
@varya ?! :(

**Comment by varya** [comment]
F*ck the notifications :-(

**Comment by varya** [comment]
I have wrapped your examples into ShadowDOM, so that they would not affect each other. We need to wait for the grammar correction (@ingdir will do this), and then can publish.
Very sorry for such a delay :-(

**Comment by varya** [comment]
http://frontendbabel.info/articles/styling-placeholder-using-css/

**Comment by talgautb** [comment]
@varya :+1:

**Comment by talgautb** [comment]
some problems with examples  @varya ff, ubuntu 14

**Comment by varya** [comment]
Could you give a screenshot?

**Pull request merged**
